[package]
name = "anytone-emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
home = "0.5.5"
log = "0.4.18"
nix = "0.26.2"
stderrlog = "0.5.4"
